name: docker-swarm-deploy
author: Elevantiq <engineering@elevantiq.com>
description: A GitHub Action that enables you to publish your app as a Docker stack to a remote Docker swarm.
inputs:
  docker_version:
    description: 'Docker CLI version (e.g., 28, 27, latest)'
    required: false
    default: '28'
  remote_host:
    description: Docker host to connect to
    required: true
  ssh_public_key:
    description: SSH public key of the server
    required: false
  ssh_private_key:
    description: SSH private key to use to connect
    required: false
  docker_registry:
    description: Log into a container registry (ghrc.io, dockerhub...)
    required: false
  docker_username:
    description: Username on the container registry
    required: false
  docker_password:
    description: Password on the container registry
    required: false
  env:
    description: set environment variables to pass to the docker command
    required: false
  run_number:
    description: github run number passed to the environment
    required: false
  args:
    description: build arguments for the stack deploy command
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
